# Generated by Django 6.0.6 on 2026-07-01 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('interval', models.CharField(default='1d', max_length=5)),
            ],
            options={
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('etf', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('signal_key', models.CharField(max_length=50)),
                ('signal_name', models.CharField(max_length=100)),
                ('exit_key', models.CharField(max_length=50)),
                ('exit_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('total_trades', models.IntegerField(default=0)),
                ('avg_return', models.FloatField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('avg_hold', models.FloatField(default=0)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('is_computed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-avg_return'],
                'unique_together': {('signal_key', 'exit_key')},
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(default='1d', max_length=5)),
                ('rsi', models.FloatField(null=True)),
                ('rsi_sma', models.FloatField(null=True)),
                ('rsi_spread', models.FloatField(null=True)),
                ('rsi_above_sma', models.BooleanField(default=False)),
                ('rsi_crossover', models.BooleanField(default=False)),
                ('crossover_days_ago', models.IntegerField(null=True)),
                ('sortino', models.FloatField(null=True)),
                ('spy_sortino', models.FloatField(null=True)),
                ('sortino_trend', models.CharField(default='flat', max_length=5)),
                ('omega', models.FloatField(null=True)),
                ('spy_omega', models.FloatField(null=True)),
                ('omega_trend', models.CharField(default='flat', max_length=5)),
                ('cvar', models.FloatField(null=True)),
                ('spy_cvar', models.FloatField(null=True)),
                ('ulcer', models.FloatField(null=True)),
                ('spy_ulcer', models.FloatField(null=True)),
                ('ulcer_trend', models.CharField(default='flat', max_length=5)),
                ('up_capture', models.FloatField(null=True)),
                ('down_capture', models.FloatField(null=True)),
                ('down_capture_trend', models.CharField(default='flat', max_length=5)),
                ('beta', models.FloatField(null=True)),
                ('gap', models.BooleanField(default=False)),
                ('gap_dir', models.CharField(max_length=5, null=True)),
                ('gap_days_ago', models.IntegerField(null=True)),
                ('gap_pct', models.FloatField(null=True)),
                ('signal', models.CharField(default='BEARISH', max_length=20)),
                ('bullish', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sector')),
            ],
            options={
                'unique_together': {('sector', 'interval')},
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='core.sector')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('sector', 'ticker')},
            },
        ),
        migrations.CreateModel(
            name='StudySectorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trades', models.IntegerField(default=0)),
                ('avg_return', models.FloatField(default=0)),
                ('total_return', models.FloatField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('avg_hold', models.FloatField(default=0)),
                ('max_gain', models.FloatField(default=0)),
                ('max_loss', models.FloatField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sector')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_results', to='core.study')),
            ],
            options={
                'unique_together': {('study', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etf', models.CharField(max_length=10)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('return_pct', models.FloatField()),
                ('hold_days', models.IntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sector')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='core.study')),
            ],
            options={
                'ordering': ['-entry_date'],
                'indexes': [models.Index(fields=['study', 'entry_date'], name='core_trade_study_i_b18218_idx'), models.Index(fields=['study', 'sector'], name='core_trade_study_i_f1e32a_idx')],
            },
        ),
    ]
