# Generated by Django 6.0.6 on 2026-07-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_candle_hypertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('annual_revenue', models.BigIntegerField(blank=True, null=True)),
                ('revenue_growth', models.FloatField(blank=True, null=True)),
                ('analyst_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('analyst_target', models.FloatField(blank=True, null=True)),
                ('analyst_count', models.IntegerField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
