# Generated by Django 6.0.6 on 2026-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fundamental'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='best_sectors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='by_curve',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='by_regime',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='by_season',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='by_spy_trend',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='by_vix',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='peak_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='peak_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='ret_90d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='sector_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='worst_sectors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
