# Generated by Django 6.0.6 on 2026-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_study_best_sectors_study_by_curve_study_by_regime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='best_peak_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='best_peak_ret',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='best_ret_90d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
