# Generated by Django 6.0.6 on 2026-07-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_study_best_peak_day_study_best_peak_ret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamental',
            name='avg_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='beta_5y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='book_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='current_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='debt_to_equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='earnings_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='enterprise_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='fifty_two_wk_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='fifty_two_wk_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='float_shares',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='forward_eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='forward_pe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='free_cash_flow',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='insider_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='institution_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='operating_cash_flow',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='operating_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='pb_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='peg_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='profit_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='ps_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='shares_outstanding',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='short_pct_float',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='short_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='total_cash',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='total_debt',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
