# Generated by Django 6.0.6 on 2026-07-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fundamental_avg_volume_fundamental_beta_5y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField()),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('earnings', models.BigIntegerField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('eps_estimate', models.FloatField(blank=True, null=True)),
                ('surprise_pct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
