# Generated by Django 6.0.6 on 2026-07-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quarterlyearnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookback_months', models.IntegerField()),
                ('hold_months', models.IntegerField()),
                ('top_n', models.IntegerField()),
                ('total_return', models.FloatField(default=0)),
                ('annual_return', models.FloatField(default=0)),
                ('spy_total', models.FloatField(default=0)),
                ('alpha', models.FloatField(default=0)),
                ('max_drawdown', models.FloatField(default=0)),
                ('num_trades', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('equity_curve', models.JSONField(blank=True, null=True)),
                ('spy_curve', models.JSONField(blank=True, null=True)),
                ('trade_log', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-total_return'],
                'unique_together': {('lookback_months', 'hold_months', 'top_n')},
            },
        ),
    ]
