# Generated by Django 6.0.6 on 2026-07-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trendstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDrilldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_trades', models.IntegerField(default=0)),
                ('stock_avg_return', models.FloatField(default=0)),
                ('stock_win_rate', models.FloatField(default=0)),
                ('stock_avg_hold', models.FloatField(default=0)),
                ('stock_max_drawdown', models.FloatField(default=0)),
                ('etf_avg_return', models.FloatField(default=0)),
                ('alpha_vs_etf', models.FloatField(default=0)),
                ('best_stocks', models.JSONField(blank=True, null=True)),
                ('worst_stocks', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drilldown', to='core.study')),
            ],
            options={
                'ordering': ['-stock_avg_return'],
            },
        ),
    ]
