# Generated by Django 6.0.7 on 2026-08-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stockdrilldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='beta_qqq',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='corr_qqq',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='corr_spy',
            field=models.FloatField(null=True),
        ),
    ]
