# Generated by Django 6.0.8 on 2026-08-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scanresult_beta_qqq_scanresult_corr_qqq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_key', models.CharField(max_length=60)),
                ('signal_name', models.CharField(max_length=120)),
                ('exit_key', models.CharField(max_length=60)),
                ('exit_name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('total_trades', models.IntegerField(default=0)),
                ('avg_return', models.FloatField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('avg_hold', models.FloatField(default=0)),
                ('universe_size', models.IntegerField(default=0)),
                ('by_dimension', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-avg_return'],
                'indexes': [models.Index(fields=['category'], name='core_stocks_categor_3c6c8e_idx'), models.Index(fields=['-avg_return'], name='core_stocks_avg_ret_0ce39b_idx')],
                'unique_together': {('signal_key', 'exit_key')},
            },
        ),
    ]
