# Generated by Django 6.0.8 on 2026-08-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stockstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('signal_key', models.CharField(max_length=60)),
                ('signal_name', models.CharField(max_length=120)),
                ('days_ago', models.IntegerField(default=0)),
                ('last_close', models.FloatField(default=0)),
                ('best_exit_key', models.CharField(blank=True, max_length=60)),
                ('hist_avg_return', models.FloatField(blank=True, null=True)),
                ('hist_win_rate', models.FloatField(blank=True, null=True)),
                ('hist_trades', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('profit_margin', models.FloatField(blank=True, null=True)),
                ('fund_buckets', models.JSONField(blank=True, null=True)),
                ('sectors', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['days_ago', '-hist_avg_return'],
                'indexes': [models.Index(fields=['signal_key'], name='core_livesi_signal__8384b3_idx'), models.Index(fields=['days_ago'], name='core_livesi_days_ag_15de98_idx')],
                'unique_together': {('ticker', 'signal_key')},
            },
        ),
    ]
