# Generated by Django 6.0.8 on 2026-08-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_livesignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('ex_date', models.DateField()),
                ('amount', models.FloatField()),
            ],
            options={
                'ordering': ['ticker', 'ex_date'],
                'unique_together': {('ticker', 'ex_date')},
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('period_end', models.DateField()),
                ('avail_date', models.DateField(db_index=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('eps_diluted', models.FloatField(blank=True, null=True)),
                ('operating_income', models.BigIntegerField(blank=True, null=True)),
                ('total_equity', models.BigIntegerField(blank=True, null=True)),
                ('total_debt', models.BigIntegerField(blank=True, null=True)),
                ('current_assets', models.BigIntegerField(blank=True, null=True)),
                ('current_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('free_cash_flow', models.BigIntegerField(blank=True, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ticker', 'period_end'],
                'indexes': [models.Index(fields=['ticker', 'avail_date'], name='core_financ_ticker_168737_idx')],
                'unique_together': {('ticker', 'period_end')},
            },
        ),
    ]
