# Generated by Django 6.0.8 on 2026-08-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dividendhistory_financialreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='cash_and_equivalents',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='cost_of_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='gross_profit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='inventory',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='operating_cash_flow',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='rd_expense',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='total_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
