# Generated by Django 6.0.8 on 2026-08-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_financialreport_cash_and_equivalents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsiderBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('filed_date', models.DateField(db_index=True)),
                ('buy_value', models.BigIntegerField(default=0)),
                ('sell_value', models.BigIntegerField(default=0)),
                ('buy_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ticker', 'filed_date'],
                'unique_together': {('ticker', 'filed_date')},
            },
        ),
    ]
