# Generated by Django 6.0.8 on 2026-08-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_insiderbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('form_group', models.CharField(db_index=True, max_length=8)),
                ('filed_date', models.DateField(db_index=True)),
                ('accession', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ['ticker', 'filed_date'],
            },
        ),
    ]
