# Generated by Django 6.0.8 on 2026-08-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_secfiling'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trendstudy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trendstudy',
            name='hold_mode',
            field=models.CharField(db_index=True, default='etf', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='trendstudy',
            unique_together={('lookback_months', 'hold_months', 'top_n', 'hold_mode')},
        ),
    ]
