# Generated by Django 6.0.8 on 2026-08-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_trendstudy_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesignal',
            name='insider_buy_90d',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesignal',
            name='recent_13d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livesignal',
            name='recent_13g',
            field=models.IntegerField(default=0),
        ),
    ]
