# Generated by Django 6.0.8 on 2026-08-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_papertrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('spot', models.FloatField(blank=True, null=True)),
                ('atm_iv', models.FloatField(blank=True, null=True)),
                ('pc_vol', models.FloatField(blank=True, null=True)),
                ('pc_oi', models.FloatField(blank=True, null=True)),
                ('n_exp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='addivergencesignal',
            new_name='core_addive_primed_7b5d42_idx',
            old_name='core_addiv_primed_idx',
        ),
        migrations.RenameIndex(
            model_name='addivergencesignal',
            new_name='core_addive_min_day_d5be7e_idx',
            old_name='core_addiv_mindays_idx',
        ),
        migrations.AddIndex(
            model_name='optionsnapshot',
            index=models.Index(fields=['ticker', 'date'], name='core_option_ticker_1bcfc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='optionsnapshot',
            unique_together={('ticker', 'date')},
        ),
    ]
