# Generated by Django 6.0.8 on 2026-08-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_optionsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsnapshot',
            name='gex',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionsnapshot',
            name='iv_skew',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionsnapshot',
            name='source',
            field=models.CharField(default='yfinance', max_length=16),
        ),
        migrations.CreateModel(
            name='DarkPoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('total_vol', models.BigIntegerField(default=0)),
                ('off_vol', models.BigIntegerField(default=0)),
                ('off_pct', models.FloatField(blank=True, null=True)),
                ('block_off_vol', models.BigIntegerField(default=0)),
                ('block_min', models.IntegerField(default=5000)),
                ('source', models.CharField(default='polygon', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'date'], name='core_darkpo_ticker_e0e75a_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
