# Generated by Django 6.0.8 on 2026-08-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_optionsnapshot_gex_optionsnapshot_iv_skew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('report_date', models.DateField(db_index=True)),
                ('eps_actual', models.FloatField(blank=True, null=True)),
                ('eps_estimate', models.FloatField(blank=True, null=True)),
                ('eps_surprise_pct', models.FloatField(blank=True, null=True)),
                ('revenue_actual', models.FloatField(blank=True, null=True)),
                ('revenue_estimate', models.FloatField(blank=True, null=True)),
                ('before_after', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'report_date'], name='core_earnin_ticker_390011_idx')],
                'unique_together': {('ticker', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='EstimateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('period', models.DateField()),
                ('period_label', models.CharField(blank=True, max_length=8)),
                ('eps_current', models.FloatField(blank=True, null=True)),
                ('eps_7d_ago', models.FloatField(blank=True, null=True)),
                ('eps_30d_ago', models.FloatField(blank=True, null=True)),
                ('revenue_avg', models.FloatField(blank=True, null=True)),
                ('asof', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'asof'], name='core_estima_ticker_81315a_idx')],
                'unique_together': {('ticker', 'period', 'asof')},
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('dt', models.DateTimeField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('pos', models.FloatField(blank=True, null=True)),
                ('neg', models.FloatField(blank=True, null=True)),
                ('neu', models.FloatField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'dt'], name='core_newsit_ticker_c3df3a_idx')],
            },
        ),
    ]
