# Generated by Django 6.0.8 on 2026-08-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_earningsevent_estimaterevision_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
