# Generated by Django 6.0.8 on 2026-08-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_newsitem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='llm_cat',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='llm_dir',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='llm_impact',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='llm_model',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='llm_rating',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
