# Generated by Django 6.0.8 on 2026-08-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_newsitem_classified_at_newsitem_llm_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='llm_horizon',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
