# Generated by Django 6.0.8 on 2026-08-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_newsitem_llm_horizon'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsHorizonSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('news_date', models.DateField()),
                ('cat', models.CharField(max_length=24)),
                ('direction', models.SmallIntegerField(default=0)),
                ('impact', models.SmallIntegerField(default=0)),
                ('horizon', models.CharField(max_length=8)),
                ('pop_pct', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('cap_bucket', models.CharField(blank=True, max_length=16)),
                ('exp_drift', models.FloatField(blank=True, null=True)),
                ('stance', models.CharField(blank=True, max_length=8)),
                ('robust', models.BooleanField(default=False)),
                ('days_since', models.IntegerField(default=0)),
                ('days_left', models.IntegerField(default=0)),
                ('last_close', models.FloatField(default=0)),
                ('title', models.CharField(blank=True, max_length=240)),
                ('sectors', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-robust', 'days_left', '-impact'],
                'indexes': [models.Index(fields=['stance'], name='core_newsho_stance_13a4b1_idx'), models.Index(fields=['robust'], name='core_newsho_robust_64705a_idx'), models.Index(fields=['cat'], name='core_newsho_cat_a71cf5_idx')],
                'unique_together': {('ticker', 'news_date', 'cat')},
            },
        ),
    ]
