# Generated by Django 6.0.8 on 2026-08-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_newshorizonsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='day_abn',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='day_effect',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
