# Generated by Django 6.0.8 on 2026-08-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_newsitem_day_abn_newsitem_day_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='day_suspect',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
    ]
