# Generated by Django 6.0.8 on 2026-08-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_newsitem_off_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='cat_auto',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='cat_llm',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
