# Generated by Django 6.0.8 on 2026-08-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_newsitem_cat_auto_alter_newsitem_cat_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='local_dir',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='local_horizon',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='local_impact',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='local_rating',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
