# Generated by Django 6.0.8 on 2026-08-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_newsitem_local_dir_newsitem_local_horizon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesignal',
            name='hist_avg_mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesignal',
            name='hist_clean_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockstudy',
            name='avg_mae',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stockstudy',
            name='clean_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='avg_mae',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='clean_pct',
            field=models.FloatField(default=0),
        ),
    ]
