# Generated by Django 6.0.8 on 2026-08-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_livesignal_hist_avg_mae_livesignal_hist_clean_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkPoolWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('week_start', models.DateField(db_index=True)),
                ('ats_shares', models.BigIntegerField(default=0)),
                ('ats_trades', models.BigIntegerField(default=0)),
                ('ats_notional', models.FloatField(blank=True, null=True)),
                ('off_pct', models.FloatField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, max_length=16)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='finra_ats', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'week_start'], name='core_darkpo_ticker_f4069a_idx')],
                'unique_together': {('ticker', 'week_start', 'source')},
            },
        ),
    ]
