# Generated by Django 6.0.8 on 2026-08-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_newseventstudy'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='latest', max_length=32, unique=True)),
                ('n_days', models.IntegerField(default=0)),
                ('n_tickers', models.IntegerField(default=0)),
                ('data', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
