# Generated by Django 6.0.8 on 2026-08-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_ivcalibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstudy',
            name='eff_trades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockstudy',
            name='t_stat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='eff_trades',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='t_stat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
