# Generated by Django 6.0.8 on 2026-08-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_stockstudy_eff_trades_stockstudy_t_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendstudy',
            name='t_stat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
