# Generated by Django 6.0.8 on 2026-08-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_trendstudy_t_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamental',
            name='eodhd_symbol',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
