# Generated by Django 6.0.8 on 2026-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_fundamental_eodhd_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamental',
            name='cik',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='cusip',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='isin',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='CongressTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('member', models.CharField(db_index=True, max_length=160)),
                ('chamber', models.CharField(blank=True, max_length=16)),
                ('party', models.CharField(blank=True, max_length=24)),
                ('state', models.CharField(blank=True, max_length=8)),
                ('transaction_type', models.CharField(db_index=True, max_length=16)),
                ('transaction_date', models.DateField(blank=True, db_index=True, null=True)),
                ('report_date', models.DateField(blank=True, db_index=True, null=True)),
                ('amount_min', models.BigIntegerField(blank=True, null=True)),
                ('amount_max', models.BigIntegerField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=24)),
                ('asset_type', models.CharField(blank=True, max_length=40)),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'report_date'], name='core_congre_ticker_74c767_idx'), models.Index(fields=['member', 'report_date'], name='core_congre_member_4be589_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('action_type', models.CharField(db_index=True, max_length=12)),
                ('ex_date', models.DateField(db_index=True)),
                ('split_ratio', models.FloatField(blank=True, null=True)),
                ('split_from', models.FloatField(blank=True, null=True)),
                ('split_to', models.FloatField(blank=True, null=True)),
                ('dividend', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('declaration_date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'ex_date'], name='core_corpor_ticker_03d2ca_idx')],
                'unique_together': {('ticker', 'action_type', 'ex_date')},
            },
        ),
        migrations.CreateModel(
            name='DelistedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('eodhd_symbol', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('exchange', models.CharField(blank=True, max_length=32)),
                ('country', models.CharField(blank=True, max_length=8)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('type', models.CharField(blank=True, max_length=40)),
                ('isin', models.CharField(blank=True, max_length=20)),
                ('delisted_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker'], name='core_delist_ticker_3a219b_idx')],
                'unique_together': {('ticker', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='MarketCapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'date'], name='core_market_ticker_de26f5_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TreasuryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('series', models.CharField(db_index=True, max_length=16)),
                ('tenor', models.CharField(max_length=8)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['series', 'date'], name='core_treasu_series_2c08ac_idx')],
                'unique_together': {('date', 'series', 'tenor')},
            },
        ),
    ]
