# Generated by Django 6.0.8 on 2026-08-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_backtestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundamental',
            name='analyst_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='analyst_hold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='analyst_rating_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='analyst_sell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='analyst_strong_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundamental',
            name='analyst_strong_sell',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
