# Generated by Django 6.0.8 on 2026-08-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_fundamental_analyst_buy_fundamental_analyst_hold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('global_score', models.FloatField(default=0)),
                ('components', models.JSONField(blank=True, null=True)),
                ('burst_signal_key', models.CharField(blank=True, max_length=60)),
                ('burst_signal_name', models.CharField(blank=True, max_length=120)),
                ('burst_type', models.CharField(default='', max_length=12)),
                ('burst_days_ago', models.IntegerField(default=0)),
                ('last_close', models.FloatField(default=0)),
                ('best_signal_key', models.CharField(blank=True, max_length=60)),
                ('hist_avg_return', models.FloatField(blank=True, null=True)),
                ('hist_win_rate', models.FloatField(blank=True, null=True)),
                ('hist_trades', models.IntegerField(blank=True, null=True)),
                ('ad_state', models.CharField(blank=True, max_length=24)),
                ('darkpool_off_pct', models.FloatField(blank=True, null=True)),
                ('darkpool_rising', models.BooleanField(default=False)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('fund_buckets', models.JSONField(blank=True, null=True)),
                ('sectors', models.JSONField(blank=True, null=True)),
                ('insider_buy_90d', models.BigIntegerField(blank=True, null=True)),
                ('recent_13d', models.IntegerField(default=0)),
                ('recent_13g', models.IntegerField(default=0)),
                ('regime_bull', models.BooleanField(default=False)),
                ('sector_state', models.CharField(blank=True, max_length=12)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-global_score'],
                'indexes': [models.Index(fields=['-global_score'], name='core_global_global__32223c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShortTermSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('signal_key', models.CharField(max_length=60)),
                ('signal_name', models.CharField(max_length=120)),
                ('burst_type', models.CharField(default='momentum', max_length=12)),
                ('days_ago', models.IntegerField(default=0)),
                ('last_close', models.FloatField(default=0)),
                ('day1_move', models.FloatField(blank=True, null=True)),
                ('z_shock', models.FloatField(blank=True, null=True)),
                ('best_exit_key', models.CharField(blank=True, max_length=60)),
                ('hist_avg_return', models.FloatField(blank=True, null=True)),
                ('hist_win_rate', models.FloatField(blank=True, null=True)),
                ('hist_trades', models.IntegerField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('fund_buckets', models.JSONField(blank=True, null=True)),
                ('sectors', models.JSONField(blank=True, null=True)),
                ('insider_buy_90d', models.BigIntegerField(blank=True, null=True)),
                ('recent_13d', models.IntegerField(default=0)),
                ('recent_13g', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['days_ago', '-hist_avg_return'],
                'indexes': [models.Index(fields=['burst_type'], name='core_shortt_burst_t_eaafab_idx'), models.Index(fields=['days_ago'], name='core_shortt_days_ag_325bde_idx')],
                'unique_together': {('ticker', 'signal_key')},
            },
        ),
    ]
