# Generated by Django 6.0.8 on 2026-08-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_globalsignal_shorttermsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningsevent',
            name='grounded_label',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='grounded_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='guidance_eps_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='revenue_surprise_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earningsevent',
            name='revenue_yoy_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
