# Generated by Django 6.0.8 on 2026-08-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_earningsevent_grounded_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsignal',
            name='intraday_rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalsignal',
            name='intraday_signal',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='intraday_rsi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='intraday_signal',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
