# Generated by Django 6.0.8 on 2026-08-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_globalsignal_intraday_rsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalFiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_key', models.CharField(max_length=60, unique=True)),
                ('signal_name', models.CharField(blank=True, max_length=120)),
                ('recent_bars', models.IntegerField(default=3)),
                ('n_firing', models.IntegerField(db_index=True, default=0)),
                ('firing', models.JSONField(blank=True, default=list)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-n_firing'],
            },
        ),
    ]
