# Generated by Django 6.0.8 on 2026-08-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_signalfiring'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('shares_out', models.BigIntegerField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('flow_shares', models.BigIntegerField(blank=True, null=True)),
                ('flow_usd', models.FloatField(blank=True, null=True)),
                ('flow_pct', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'date'], name='core_etfflo_ticker_df5a92_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
