# Generated by Django 6.0.8 on 2026-08-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_etfflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['series', 'date'], name='core_macros_series_da53e9_idx')],
                'unique_together': {('series', 'date')},
            },
        ),
    ]
